### PR TITLE
Adds collections metadata

### PR DESCRIPTION
**Pull request by tersmitten**
Does not work in Ansible < 2.8

### CODE REVIEW

**Comment by nkakouros** [comment]
Does it break sth? In my tests, it is simply ignored by earlier versions of ansible.

**Comment by tersmitten** [comment]
That's true, but not by ansible < 2.8

**Comment by tersmitten** [comment]
Can you make this up-2-date? `2.8` is not the minimal version :-)

**Comment by nkakouros** [comment]
Since I created this PR, I came to prefer namespace module names in tasks instead of using the `collections` key. For instance, instance of having a task like:

```yaml
- name: Upload file
  copy:
    ...
```

it would become:

```yaml
- name: Upload file
  ansible.builtin.copy:
    ...
```

I think this syntax is supported in ansible >= 2.9. Is this the minimum version you are targeting? If so, I could rewrite the modules if you think it is preferable.

**Comment by tersmitten** [comment]
Fixed in #31

**Pull request closed without merging**
