### PR TITLE
Make UNIX permission mode bits configurable for public and private keys

### PR DESCRIPTION
**Pull request by mvdriel**

### CODE REVIEW

**Comment by tersmitten** [comment]
@mvdriel why did you close it?

**Comment by mvdriel** [comment]
@tersmitten I'm not sure whether it is desirable to make private keys accessible for other users.

**Comment by mvdriel** [comment]
@tersmitten For cacti it is probably better to use public/private keys of www-data (in /var/www/.ssh/). Then there is no need to specify a group or permissions.

**Comment by tersmitten** [comment]
@mvdriel That's how we've set it up I think.

**Pull request merged**
